name: Build Latest chaos-mesh.dev-godoc Docker Image

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image for godoc
      run: make image-godoc
    - name: Push docker image to ghcr.io
      run: docker push ghcr.io/strrl/chaos-mesh.dev-godoc:latest
