name: Manually Generate godoc
on:
  workflow_dispatch:
    inputs:
      branchOrTag:
        description: The branch or tag of Chaos Mesh.
        required: true
        default: master

jobs:
  godoc: 
    name: "Generate godoc for: ${{ github.event.inputs.branchOrTag }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate godoc
      run: |
        mkdir -p out/godoc
        docker run -v $(pwd)/out/godoc:/playground/out ghcr.io/strrl/chaos-mesh.dev-godoc:latest ${{ github.event.inputs.branchOrTag }}
    - name: change permission of these files
      run: |
        sudo chmod -R 755 out
    - name: publish to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out/godoc/${{ github.event.inputs.branchOrTag }}
        destination_dir: godoc/${{ github.event.inputs.branchOrTag }}
        disable_nojekyll: true
