name: Generate xml sitemap
on:
  workflow_dispatch: {}
  push:
    branches:
      - gh-pages

jobs:
  sitemap:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: placeholder on master
      uses: mstachniuk/ci-skip@v1
